query servers {
  servers {
    id
    name
    url
    port
  }
}

query server($id: String!) {
  server(id: $id) {
    id
    name
    url
    port
  }
}

mutation addServer($input: ServerInput!) {
  addServer(input: $input) {
    id
    name
    url
    port
  }
}

mutation updateServer($input: ServerInput!, $id: String!) {
  updateServer(input: $input, id: $id) {
    id
    name
    url
    port
  }
}

mutation deleteServer($id: String!) {
  deleteServer(id: $id) {
    id
    name
    url
    port
  }
}
